import pytest
import sys, os

from exercises.e05.e05_doc import Protein

def test_get_sequence_1():

    protein = Protein("P32249", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e05/P32249.xml")
    fasta = protein.get_sequence()
    fasta_solution = "MDIQMANNFTPPSATPQGNDCDLYAHHSTARIVMPLHYSLVFIIGLVGNLLALVVIVQNRKKINSTTLYSTNLVISDILFTTALPTRIAYYAMGFDWRIGDALCRITALVFYINTYAGVNFMTCLSIDRFIAVVHPLRYNKIKRIEHAKGVCIFVWILVFAQTLPLLINPMSKQEAERITCMEYPNFEETKSLPWILLGACFIGYVLPLIIILICYSQICCKLFRTAKQNPLTEKSGVNKKALNTIILIIVVFVLCFTPYHVAIIQHMIKKLRFSNFLECSQRHSFQISLHFTVCLMNFNCCMDPFIYFFACKGYKRKVMRMLKRQVSVSISSAVKSAPEENSREMTETQMMIHSKSSNGK"

    assert fasta == fasta_solution

def test_get_sequence_2():

    protein = Protein("", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e05/P32249.xml")
    fasta = protein.get_sequence()

    assert fasta == ""

def test_get_sequence_3():

    protein = Protein("DS", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e05/P32249.xml")
    fasta = protein.get_sequence()

    assert fasta == ""

def test_import_amino_acid_properties_and_create_hydropathy_dict_1():

    protein = Protein("P32249", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e03/P32249.xml")
    hydropathy_dict = protein.import_amino_acid_properties_and_create_hydropathy_dict()

    assert hydropathy_dict == {'A': 1.8, 'R': -4.5, 'N': -3.5, 'D': -3.5, 'C': 2.5, 'E': -3.5, 'Q': -3.5, 'G': -0.4, 'H': -3.2, 'I': 4.5, 'L': 3.8, 'K': -3.9, 'M': 1.9, 'F': 2.8, 'P': -1.6, 'S': -0.8, 'T': -0.7, 'W': -0.9, 'Y': -1.3, 'V': 4.2}


def test_import_amino_acid_properties_and_create_hydropathy_dict_2():

    protein = Protein("P32249", 5, "", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e03/P32249.xml")
    hydropathy_dict = protein.import_amino_acid_properties_and_create_hydropathy_dict()

    assert hydropathy_dict == {}

def test_create_hydropathy_value_list_for_fasta_1():

    protein = Protein("P32249", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e03/P32249.xml")
    hydropathy_dict = {'A': 1.8, 'R': -4.5, 'N': -3.5, 'D': -3.5, 'C': 2.5, 'E': -3.5, 'Q': -3.5, 'G': -0.4, 'H': -3.2,
                        'I': 4.5, 'L': 3.8, 'K': -3.9, 'M': 1.9, 'F': 2.8, 'P': -1.6, 'S': -0.8, 'T': -0.7, 'W': -0.9,
                        'Y': -1.3, 'V': 4.2}
    fasta = "MDIQMANNFTPPSATPQGNDCDLY"
    hydropathy_sequence_list = protein.create_hydropathy_value_list_for_fasta(fasta, hydropathy_dict)
    hydropathy_sequence_list_solution = [1.9,
 -0.8,
 0.9666666666666667,
 -0.15000000000000002,
 0.25999999999999995,
 0.24,
 0.24000000000000005,
 -1.3599999999999999,
 -0.1,
 -0.6200000000000001,
 -1.3,
 -0.9199999999999999,
 -0.3800000000000001,
 -0.5800000000000001,
 -0.5800000000000001,
 -0.5800000000000001,
 -0.96,
 -0.8800000000000001,
 -1.94,
 -2.5,
 -1.6800000000000002,
 -1.6800000000000002,
 -0.8400000000000001,
 -0.4]

    assert hydropathy_sequence_list == hydropathy_sequence_list_solution

def test_create_hydropathy_value_list_for_fasta_2():

    protein = Protein("P32249", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e03/P32249.xml")
    hydropathy_dict = {'A': 1.8, 'R': -4.5, 'N': -3.5, 'D': -3.5, 'C': 2.5, 'E': -3.5, 'Q': -3.5, 'G': -0.4, 'H': -3.2,
                        'I': 4.5, 'L': 3.8, 'K': -3.9, 'M': 1.9, 'F': 2.8, 'P': -1.6, 'S': -0.8, 'T': -0.7, 'W': -0.9,
                        'Y': -1.3, 'V': 4.2}
    hydropathy_sequence_list = protein.create_hydropathy_value_list_for_fasta("", hydropathy_dict)

    assert hydropathy_sequence_list == []

def test_create_hydropathy_value_list_for_fasta_3():

    protein = Protein("P32249", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e03/P32249.xml")
    hydropathy_sequence_list = protein.create_hydropathy_value_list_for_fasta("MDIQMANNFTPPSATPQGNDCDLYAHHSTARIVMPLHYSLVFIIGLVGNLLALVVIVQNRKKINSTTLYSTNLVISDILFTTALPTRIAYYAMGFDWRIGDALCRITALVFYINTYAGVNFMTCLSIDRFIAVVHPLRYNKIKRIEHAKGVCIFVWILVFAQTLPLLINPMSKQEAERITCMEYPNFEETKSLPWILLGACFIGYVLPLIIILICYSQICCKLFRTAKQNPLTEKSGVNKKALNTIILIIVVFVLCFTPYHVAIIQHMIKKLRFSNFLECSQRHSFQISLHFTVCLMNFNCCMDPFIYFFACKGYKRKVMRMLKRQVSVSISSAVKSAPEENSREMTETQMMIHSKSSNGK", {})

    assert hydropathy_sequence_list == []

def test_extract_xml_and_extract_topological_domains_1():

    protein = Protein("P32249", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "")
    domain_sites_list = protein.extract_xml_and_extract_topological_domains()

    assert domain_sites_list == []

def test_extract_xml_and_extract_topological_domains_2():

    protein = Protein("P32249", 5, "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/data/amino_acid_properties.csv", "C:/Users/lucas/PycharmProjects/fufezan-lab-advanced_python_2020-21_HD/exercises/e03/P32249.xml")
    domain_sites_list = protein.extract_xml_and_extract_topological_domains()
    domain_sites_list_solution = ['topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'transmembrane_region_sites',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site',
 'topological_domain_site']

    assert domain_sites_list == domain_sites_list_solution


